=== Laquijano8/SemanticWebinAction/02 - XML - RDF/Solución XML/AppEjemploXML/Ejemplos 2/04-xsd/MisContactos.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="lista">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Contacto">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="pais" type="xs:string" />
              <xs:element name="Departamento" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Laquijano8/SemanticWebinAction/02 - XML - RDF/Solución XML/AppEjemploXML/Ejemplos 2/03-xml/MisContactos.xml
<?xml version="1.0" encoding="utf-8" ?>
<lista  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../04-xsd/MisContactos.xsd">
  <Contacto>
    <nombre>Juan Espinosa</nombre>
    <pais>Mexico</pais>
    <Departamento>Sistemas</Departamento>
  </Contacto>
  <Contacto>
    <nombre>Carlos Cobos</nombre>
    <pais>Colombia</pais>
    <Departamento>Sistemas</Departamento>
  </Contacto>
  <Contacto>
    <nombre>Juan Manuel</nombre>
    <pais>Colombia</pais>
    <Departamento>Informartica</Departamento>
  </Contacto>

</lista>
